### ISSUE TITLE
Can't build with yarn

### ISSUE THREAD

**Issue by KartoniarzEssa** [darkwire/darkwire.io#227] opened 2022-12-28 17:47 UTC
chuj@chuj:~/darkwire.io$ yarn build
yarn run v1.22.19
$ ./build.sh
building client...
[1/4] Resolving packages...
success Already up-to-date.
$ tsc && vite build
src/main.tsx:12:28 - error TS2307: Cannot find module '@/store/' or its corresponding type declarations.

12 import configureStore from '@/store/';
                              ~~~~~~~~~~

src/main.tsx:13:18 - error TS2307: Cannot find module '@/components/Home/' or its corresponding type declarations.

13 import Home from '@/components/Home/';
                    ~~~~~~~~~~~~~~~~~~~~

src/main.tsx:14:33 - error TS2307: Cannot find module '@/utils/dom' or its corresponding type declarations.

14 import { hasTouchSupport } from '@/utils/dom';
                                   ~~~~~~~~~~~~~


Found 3 errors in the same file, starting at: src/main.tsx:12

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
building server...
[1/4] Resolving packages...
success Already up-to-date.
$ echo 'Nothing to build here.'
Nothing to build here.
Done in 4.83s.

**Comment by KartoniarzEssa** [comment] 2022-12-29 11:39
I fixed everything by changing
```
import configureStore from '@/store/';
import Home from '@/components/Home/';
import { hasTouchSupport } from '@/utils/dom';
```
to
```
import configureStore from './store/';
import Home from './components/Home/';
import { hasTouchSupport } from './utils/dom';
```
then when yarn build worked i linked client/dist folder to client/build using command below
`ln -s client/dist client/build`
then the darkwire worked

**Comment by jrmi** [comment] 2022-12-29 13:46
Thanks for reporting @KartoniarzEssa It should be fixed now. Let me know if you experience new trouble.

**Closed** 2022-12-29 13:45 UTC

**Comment by KartoniarzEssa** [comment] 2022-12-29 14:28
> Thanks for reporting @KartoniarzEssa It should be fixed now. Let me know if you experience new trouble.

Now building the Dockerfile have problem because you change the container to alpine that have apk as package manager not apt. To fix it you must change to debian-based distro.

**Comment by KartoniarzEssa** [comment] 2022-12-29 20:16
@jrmi Also, there are 2 more errors that i don't know how to resolve, first is only some warnings but idk if they're important
![image](https://user-images.githubusercontent.com/81422890/210006994-ea81cf39-6353-485d-aa7e-b0f640309619.png)
![image](https://user-images.githubusercontent.com/81422890/210007052-8009efb3-7c47-4845-b627-27398bd45c31.png)

**Comment by jrmi** [comment] 2022-12-29 20:28
Thanks again for reporting. The error you're seeing during the build are more a warning because of some obsolete dependencies (I'm trying to replace them) and because of the final size of the build. These two are not blocking I guess.

The error you're experiencing in your browser is probably caused by the fact you're accessing Darkwire through a http connection.  Check out this issue #195 you'll see the same error. If you want to solve that you should use a httpS connection. I should make the error more clear or may be use something like https://www.npmjs.com/package/webcrypto-shim in this case.

**Comment by KartoniarzEssa** [comment] 2022-12-29 20:55
@jrmi Ok now I have a certificate and a https, even I'am listed in a room and I can text but after refresh everything disappears, and it says that it's disconnected idk from what. Redis? API?
![image](https://user-images.githubusercontent.com/81422890/210010110-ce924fe4-9083-4b6d-8ed6-9bb48b2829d0.png)

**Comment by jrmi** [comment] 2022-12-29 21:33
This message is displayed when you are disconnected from the websocket. Redis is not used anymore. If you've used a reverse proxy to add the certificate and the https you probably also need some configuration to make the websockets work. What have you used as proxy?

**Comment by KartoniarzEssa** [comment] 2022-12-29 21:39
@jrmi I used nginx and this is config
![image](https://user-images.githubusercontent.com/81422890/210013547-8bc8bf3b-8597-4492-b194-b151a3b55a91.png)

**Comment by jrmi** [comment] 2022-12-29 21:42
Take a look at this link https://www.nginx.com/blog/websocket-nginx/
I think this configurations are missing:
```
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
```
May be more.

**Comment by jrmi** [comment] 2022-12-29 21:43
Or this link https://nginx.org/en/docs/http/websocket.html

**Comment by jrmi** [comment] 2022-12-29 21:54
I've published a new version with a fixed version of docker file and docker compose and I've applied your suggestion to the readme. Let me know what you think.

**Comment by KartoniarzEssa** [comment] 2022-12-29 22:03
little typos
![image](https://user-images.githubusercontent.com/81422890/210015233-d1d08e85-aaad-4476-9544-99b0f2d25f45.png)

**Comment by KartoniarzEssa** [comment] 2022-12-29 22:05
And I think i found the problem, idk what that means tho
![image](https://user-images.githubusercontent.com/81422890/210015405-0dbf58f1-eaea-48d6-9953-0a8db7887695.png)

**Comment by jrmi** [comment] 2022-12-29 22:07
nvm is not a typo it's a tool to manage node version. Was it the typo?

**Comment by KartoniarzEssa** [comment] 2022-12-29 22:08
Oh i thought its meant to be npm

**Comment by KartoniarzEssa** [comment] 2022-12-29 22:09
> And I think i found the problem, idk what that means tho ![image](https://user-images.githubusercontent.com/81422890/210015405-0dbf58f1-eaea-48d6-9953-0a8db7887695.png)

This is probably CORS

**Comment by jrmi** [comment] 2022-12-29 22:10
Yeah something like that. Or content security policy are wrong. Sometimes it also shows that when there is no websocket server at all. Are you trying a localhost version?

**Comment by KartoniarzEssa** [comment] 2022-12-29 22:13
Where can I change this localhost to my domain

This is client .env file
![image](https://user-images.githubusercontent.com/81422890/210015824-fc3c1b4d-b283-45b3-a505-93304500f6f9.png)

And this is server .env file
![image](https://user-images.githubusercontent.com/81422890/210015944-457b009e-4a4f-47bc-a53a-8c05bf023aca.png)

**Comment by jrmi** [comment] 2022-12-29 22:20
It should be in the client .env file. But you might have to recreate your docker image (if you are using docker).

**Comment by jrmi** [comment] 2022-12-29 22:21
You might have to recreate you docker image from scratch also. (docker build...)

**Comment by KartoniarzEssa** [comment] 2022-12-29 22:21
Now Im not even using docker

**Comment by KartoniarzEssa** [comment] 2022-12-29 22:21
for now

**Comment by KartoniarzEssa** [comment] 2022-12-29 22:22
My domain should be in VITE_API_HOST?

**Comment by jrmi** [comment] 2022-12-29 22:22
Yes. 
Can you describe me what is your setup?

**Comment by KartoniarzEssa** [comment] 2022-12-29 22:23
I just starting it by using yarn start in darkwire.io folder

**Comment by jrmi** [comment] 2022-12-29 22:24
Ok so you might have to execute `yarn build` again to update the build with the right env var.

**Comment by KartoniarzEssa** [comment] 2022-12-29 22:24
every change i run ./build.sh

**Comment by KartoniarzEssa** [comment] 2022-12-29 22:27
Seems like its ignoring .env file
![image](https://user-images.githubusercontent.com/81422890/210016984-aa86bd49-5596-4f5a-9f43-8d7e9a29a047.png)

**Comment by jrmi** [comment] 2022-12-29 22:30
Remove the `client/dist` dir to check it break the server and then rebuild it?

**Comment by KartoniarzEssa** [comment] 2022-12-29 22:31
yup it breaks
![image](https://user-images.githubusercontent.com/81422890/210017260-098aafdf-f85f-44df-966b-1b6e7f7ac287.png)

**Comment by KartoniarzEssa** [comment] 2022-12-29 22:32
After rebuild same error in console

**Comment by jrmi** [comment] 2022-12-29 22:51
Can you try to rebuild the client from it's own directory?
```
cd client
yarn build
cd ..
yarn start
```

**Comment by KartoniarzEssa** [comment] 2022-12-29 22:57
Now its working but not, the error is the same
![image](https://user-images.githubusercontent.com/81422890/210018913-a64528d9-7a4d-4bb1-924d-29defe3ba8b7.png)

**Comment by jrmi** [comment] 2022-12-29 22:59
What do you see if you visit `https://yourdomain/socket.io/` ?

**Comment by KartoniarzEssa** [comment] 2022-12-29 23:00
![image](https://user-images.githubusercontent.com/81422890/210019191-37d4345d-9c41-41cc-8b26-e238bdfdd3ba.png)

**Comment by KartoniarzEssa** [comment] 2022-12-29 23:01
But its without port in the console its with port

**Comment by KartoniarzEssa** [comment] 2022-12-29 23:02
And maybe this is problem

**Comment by jrmi** [comment] 2022-12-29 23:03
But if you're behind a nginx reverse proxy, you might need no port (or port 443).

**Comment by jrmi** [comment] 2022-12-29 23:03
What is the url you use in the browser?

**Comment by KartoniarzEssa** [comment] 2022-12-29 23:03
its without port, but in console the error is with port

**Comment by jrmi** [comment] 2022-12-29 23:04
So remove the port!

**Comment by jrmi** [comment] 2022-12-29 23:04
(use 443)

**Comment by KartoniarzEssa** [comment] 2022-12-29 23:04
OK I set the port in client .env to 443 and its working
![image](https://user-images.githubusercontent.com/81422890/210019435-a4891132-c1e6-4353-9779-f8a514981075.png)

**Comment by KartoniarzEssa** [comment] 2022-12-29 23:05
Thanks for support and help

**Comment by jrmi** [comment] 2022-12-29 23:05
Congrats :) and good night. I have published a version that fix the build problem not using `.env` file FYI.

**Comment by KartoniarzEssa** [comment] 2022-12-29 23:09
I also translate the panel to polish if you want
```
{
"newRoomButton": "Nowy pokój",
"lockedRoom": "{username} zablokował pokój",
"unlockedRoom": "{username} odblokował pokój",
"agreement": "Korzystając z darkwire, zgadzasz się na naszą politykę zasad korzystania i warunki korzystania",
"typePlaceholder": "Pisz tutaj",
"aboutButton": "O nas",
"settingsButton": "Ustawienia",
"settings": "Ustawienia",
"aboutHeader": "O nas",
"copyButtonTooltip": "Skopiowano",
"welcomeHeader": "Witamy na czacie Starymisiada",
"sentFile": "Wysłałeś {filename}",
"userJoined": "{username} dołączył",
"userLeft": "{username} opuścił",
"userSentFile": "{username} wysłał Ci plik.",
"downloadFile": "Pobierz {filename}",
"nameChange": "{oldUsername} zmienił swoje imię na {newUsername}",
"settingsHeader": "Ustawienia & Pomoc",
"copyRoomHeader": "Ten pokój",
"languageDropdownHeader": "Język",
"roomOwnerHeader": "Własność pokoju",
"roomOwnerText": "Osoba, która utworzyła pokój, jest właścicielem pokoju i ma specjalne uprawnienia, takie jak możliwość zablokowania i odblokowania pokoju. Jeśli właściciel opuści pokój, druga osoba, która dołączy, przejmuje własność. Jeśli ona opuści, trzecia osoba staje się właścicielem itd. Właściciel pokoju ma ikonę gwiazdki obok swojej nazwy użytkownika w rozwijanej liście uczestników.",
"lockRoomHeader": "Zablokuj pokój",
"lockRoomText": "Jeśli jesteś właścicielem pokoju, możesz zablokować i odblokować pokój, klikając ikonę zamka w pasku nawigacyjnym. Gdy pokój jest zablokowany, żadna inna osoba nie może do niego dołączyć.",
"slashCommandsHeader": "Komendy",
"slashCommandsText": "Dostępne są następujące komendy:",
"slashCommandsBullets": [
"zmienia nazwę użytkownika",
"wykonuje akcję",
"czyści historię wiadomości",
"wyświetla wszystkie komendy"
],
"sound": "Dźwięk",
"newMessageNotification": "Powiadomienie o nowej wiadomości",
"desktopNotification": "Powiadomienie na pulpicie",
"desktopNotificationBlocked": "Powiadomienia na pulpicie zostały wyłączone",
"welcomeModalCTA": "Ok",
"lockedRoomHeader": "Ten pokój jest zablokowany",
"helpTranslate": "Pomóż nam przetłumaczyć darkwire!"
}
```

**Comment by jrmi** [comment] 2022-12-30 06:40
Great! Would you mind review this MR #231
